services:
  media-compressor:
    container_name: media-compressor
    image: ghcr.io/francisjgarcia/media-compressor:local
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.local
    env_file:
      - .env
      - ../src/.env
    volumes:
      - ../src:/app
      - ../tests:/app/tests
    user: root
    privileged: true
    tty: true
    entrypoint: ["/bin/sh", "-c"]
    command: /bin/sh
    restart: on-failure
